# Generated by Django 4.2.3 on 2023-07-04 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_created=True)),
                ('nama_kategori', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Postingan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_created=True)),
                ('judul', models.CharField(max_length=100)),
                ('gmbar', models.ImageField(upload_to='img')),
                ('konten', models.TextField()),
                ('create_at', models.DateField(auto_now_add=True)),
                ('kategori', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='api.kategori')),
                ('penulis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
