# Generated by Django 4.2.3 on 2023-07-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postingan',
            name='update_at',
            field=models.DateField(auto_now=True),
        ),
    ]
